services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: taskflow
    volumes:
      - taskflow_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" 
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    depends_on: ["db"]
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/taskflow 
      - CLIENTS=http://localhost:5173 
      - JWT_SECRET=your-secret-key
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
volumes:
  taskflow_postgres_data: