from node:22-slim as builder
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

FROM node:22-slim as runner
RUN apt-get update -y && apt-get install -y openssl
WORKDIR /app

COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/package-lock.json ./package-lock.json

RUN npm install --omit=dev

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/prisma.config.ts ./prisma.config.ts
RUN npx prisma generate

CMD ["sh", "-c", "npx prisma migrate deploy && npm run seed && npm run start"]